name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install dependencies
        run: npm install
      - name: Run app
        run: npm start
      - name: Run test
        run: npm test
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
